### ISSUE TITLE
add version name to the zip/gzip files we use for the releases.

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenopacket-store#119]

**Comment by ielis** [comment]
Will this play well with the concept of downloading the latest release?

As pointed out in #95 , we can use an URL like

https://github.com/monarch-initiative/phenopacket-store/releases/latest/download/all_phenopackets.tgz

to download the latest release. 

However, if we add version to the archive name, the link may not stay stable.

Instead, of adding the version name to the archive name, we should add the version to the name of the *top level folder*, added by #96
