### ISSUE TITLE
Possible duplicate patient in **COL6A1** and **COL6A3** cohorts

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/phenopacket-store#122]
The patient `PMID_17886299_patient_BM5` seem to be included in two cohorts. 

The patient  is included in both COL6A1 and COL6A3 cohorts:
- [COL6A1](https://github.com/monarch-initiative/phenopacket-store/blob/main/notebooks/COL6A1/phenopackets/PMID_17886299_patientBM5.json)
- [COL6A3](https://github.com/monarch-initiative/phenopacket-store/blob/main/notebooks/COL6A3/phenopackets/PMID_17886299_patientBM5.json)

The patient is not a simple duplicate, but there are true differences between the phenopackets despite sharing the same ID.  The phenopackets report different times at last encounter, different mutations in different genes, and different phenotypic features (e.g. Scoliosis is [present](https://github.com/monarch-initiative/phenopacket-store/blob/2dfb1303ba1f84eecaeec4131204ec6d11c075e4/notebooks/COL6A1/phenopackets/PMID_17886299_patientBM5.json#L38) in COL6A1 but [excluded](https://github.com/monarch-initiative/phenopacket-store/blob/2dfb1303ba1f84eecaeec4131204ec6d11c075e4/notebooks/COL6A3/phenopackets/PMID_17886299_patientBM5.json#L78) in COL6A3).

The possible duplicity was pointed out by PR #121

**Comment by pnrobinson** [comment]
BM5 has a COL6A1 mutation and should not be in the COL6A3 cohort. I will remove and check the annotations in COL6A1

**Comment by pnrobinson** [comment]
fixed
