### ISSUE TITLE
Error in ppkt

### ISSUE THREAD

**Issue by leokim-l** [monarch-initiative/phenopacket-store#146]
@pnrobinson 
In PMID_30095615_proband.json there are some \t characters that are interpreted as tabs 

https://github.com/monarch-initiative/phenopacket-store/blob/2c58388a9312092df2c7f3b71b74aaac60ac7b1a/notebooks/CRX/phenopackets/PMID_30095615_proband.json#L155

leading to extra-tab errors in MALCO when we have the disease label as one entry of a dataframe:

https://github.com/monarch-initiative/malco/blob/5c3ca68ef0bb12da2bf3cccbdaf9a3500a293b39/src/malco/post_process/ranking_utils.py#L66

**Comment by pnrobinson** [comment]
Fixed this error, it will be repaired with the next release
@ielis  Would be it easy to add a Q/C check with the CI that throws an error if there is a tab in any of the components of the phenopackets? This one came from the way I am constructing the Excel template, but we should rule out tabs especially in the disease name and in the PubMed titles?

**Comment by ielis** [comment]
Yeah, will implement [here](https://github.com/monarch-initiative/phenopacket-store-toolkit/issues/5).

**Comment by ielis** [comment]
Done in [here](https://github.com/monarch-initiative/phenopacket-store-toolkit/pull/7), will be included in Phenopacket Store CI from the next release.

**Comment by leokim-l** [comment]
I think I just caught another one, is this fixed in the next release?

https://github.com/monarch-initiative/phenopacket-store/blob/8e69b52edd72a700e9b07a6de91cda6b0e8821e3/notebooks/CAD/phenopackets/PMID_25678555_UDP4003.json#L223

**Comment by pnrobinson** [comment]
Fixed, also added unit test to prevent this in the future.
