### ISSUE TITLE
Possible issue with reference range in CYP21A2

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/phenopacket-store#152]
The pydoc of the `testosterone_assessment` function of the 5th cell of the [CYP21A2 notebook](https://github.com/monarch-initiative/phenopacket-store/blob/main/notebooks/CYP21A2/CYP21_Xu_2019.ipynb) states the reference values to:

```
Male: 300 to 1,000 nanograms per deciliter (ng/dL)
Female: 15 to 70 nanograms per deciliter (ng/dL)
```

However, the reference range in the notebooks (e.g. [here](https://github.com/monarch-initiative/phenopacket-store/blob/c3d6350ee1ddb98df750bbbf6e288a118166b675/notebooks/CYP21A2/phenopackets/PMID_30968594_individual_1.json#L79) or [here](https://github.com/monarch-initiative/phenopacket-store/blob/c3d6350ee1ddb98df750bbbf6e288a118166b675/notebooks/CYP21A2/phenopackets/PMID_30968594_individual_13.json#L59)) includes:

```
"referenceRange": {
  "unit": {
    "id": "UCUM:ng/dL",
    "label": "nanogram per deciliter"
  },
  "low": 3.0,
  "high": 10.0
}
```

which looks incorrect.

**Comment by pnrobinson** [comment]
fixed with release 0.1.20
