### ISSUE TITLE
WWOX notebooks

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenopacket-store#25]
PMID_25411445  -- this notebook contains data about the PMID_17470496
Is the original file available somewhere?

**Comment by pnrobinson** [comment]
@ldingemans  updates?

**Comment by ldingemans** [comment]
maybe I misunderstood - I send you one on Sep 20 to try and schedule a meeting, but I did not get a reply I think?
I can send you another one to reschedule of course but not sure what is best?

**Comment by pnrobinson** [comment]
I have revised all of the scripts and notebooks over the last few weeks and added a lot of Q/C code to pyphetools, and I think things are now correct. For now let's concentrate on finishing the analysis. I will continue to add data to the repo.
