### ISSUE TITLE
A supplement table with potentially usable case reports

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/phenopacket-store#41]
@pnrobinson the supplement table S1 of the paper has potentially useful case reports.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7173875/

A screenshot with a table excerpt:

![image](https://github.com/monarch-initiative/phenopacket-store/assets/12170955/760d262d-d7fc-43fe-80aa-4063fb86e6c6)

**Comment by pnrobinson** [comment]
This data was included in PRIORI-T and seems to be the only dataset that we can easily use from that. I have added the OMIM ids.

**Comment by pnrobinson** [comment]
After a closer look, the data is not always consistent and some of the rows appear pretty noisy. I think it is easier to look elsewhere.
