### ISSUE TITLE
SLC2A1 - potential candidate gene for genotype phenotype correlation

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/phenopacket-store#59]
[Glucose transporter-1 deficiency syndrome: the expanding clinical and genetic spectrum of a treatable disorder](https://academic.oup.com/brain/article/133/3/655/275024?login=false)  is a paper with potential genotype-phenotype correlations between missense vs nonsense variants in *SLC2A1*.

The authors of suggest presence of three different phenotypes in their cohort of 57 patients with *SLC2A1* mutations:
- the *classical* phenotype (84%), further divided into 
  - early-onset (<2 years) (65%)
  - late-onset (18%)
- a *non-classical* phenotype, with mental retardation and movement disorder, without epilepsy (15%)
- one adult case of glucose transporter-1 deficiency syndrome with minimal symptoms

The data is present in several tables:

**Table 1** includes HGVS mutations, links the mutations to patients and assigns the phenotype group.

**Table 2** describes 36 subjects with the *classical* phenotype

**Table 3** describes 8 patients with the *non-classical* phenotype

Perhaps this can be useful for GPC?

**Comment by pnrobinson** [comment]
I do not think we can easily use this paper because the authors summarize the phenotypes into their own groups and this cannot be coded as HPO. We have enough other cohorts, so I am closing this.
