### ISSUE TITLE
LMNA

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenopacket-store#63]
Remove Barthelemy (atypical course which muddies the waters) @ielis  -- make copy if need be.

**Comment by pnrobinson** [comment]
Remove Novelli since it is one patient. with incomplete clinical description @ielis

**Comment by pnrobinson** [comment]
Remove Patni (it is a novel syndrome not yet listed in OMIM) @ielis

**Comment by pnrobinson** [comment]
Remove Simha (it is a mixed phenotype that does not match exactly with existing OMIM identifiers). There are quite a few of these kinds of case reports but it is hard now to know what to do with them and the clinical descriptions are heterogeneous and perhaps best left for a separate study. @ielis

**Comment by pnrobinson** [comment]
@ielis  remove Van Esch -- a novel syndrome of arthropathy, tendinous calcinosis, and progeroid features. (see above comment)

Remove Zirn -- same comment

**Comment by pnrobinson** [comment]
@ielis I would also tend to remove Wiltshire, since only one individual is described in detail, which necessarily adds to apparent hetergeneity (no way to know)

**Comment by pnrobinson** [comment]
We have the following diseases

- Cardiomyopathy, dilated, 1A 	115200 	AD 	3
- Emery-Dreifuss muscular dystrophy 2, autosomal dominant 	181350 	AD 	3
- Hutchinson-Gilford progeria 	176670 	AD 	3
- Lipodystrophy, familial partial, type 2 

We have over 10 individuals for each disease except the last (I have reached out to two authors of large cohorts for the last). I would suggest we delete the rest, since it is hard to judge the effects with small groups of other diseases (e.g., Emery-Dreifuss recessive). Please save the files in data elsewhere, and we should remove them for now from here!

**Comment by ielis** [comment]
Hi, thanks a lot for the phenopackets! I'll add these into the pipeline.

**Comment by pnrobinson** [comment]
I still need to fix a few minor errors and export the final LMNA phenopackets. If you are ok, I will delete the files and will be adding more cohorts of LMNA this week.

**Comment by ielis** [comment]
Yes, please go forward with deleting the files and adding more _LMNA_ cohorts.

**Comment by pnrobinson** [comment]
done
