### ISSUE TITLE
Dead links in documentation for contributors

### ISSUE THREAD

**Issue by hansenp** [monarch-initiative/phenopacket-store#83]
In the [contributor section](https://monarch-initiative.github.io/phenopacket-store/contributing/), the `phenopacket-store` documentation contains some dead links:

- https://monarch-initiative.github.io/phenopacket-store/contributing/variant_notation.md
- https://monarch-initiative.github.io/phenopacket-store/contributing/excel.md
- https://monarch-initiative.github.io/phenopacket-store/contributing/python_notebook.md
- https://monarch-initiative.github.io/phenopacket-store/contributing/tips_for_curation.md

However, I find comparable sections in the documentation of `pyphetools`. To me it looks like someone wanted to restructure the documentation of `pyphetools` and `phenopacket-store` but didn't finish it.

It should be clarified first which documentation belongs to `pyphetools` and which to `phenopacket-store` and then it should be cleaned up accordingly.

**Comment by ielis** [comment]
The links are not dead anymore (for now 🙃), and they include somewhat relevant info for potential Phenopacket store contributors. So, I'll close this as complete.
