### ISSUE TITLE
Add pipeline for ingesting from Molecular Case Studies (MCS) papers

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/phenopacket-store#85]
E.g

https://molecularcasestudies.cshlp.org/content/9/4/a006294.full

All MCS case reports have HPO IDs pre-annotated.

Of course manual curation is required to capture the individuals but it could still be useful to have a placeholder phenopacket as the g2p relationship is potentially useful

**Comment by pnrobinson** [comment]
It would also be great to see if we can develop an LLM powered tool to decipher tables such as this:
https://molecularcasestudies.cshlp.org/content/9/4/a006294/T1.expansion.html
We also need to extract the variants. I  think that Z. Liu at NLM had a good tool for that. 
Love this idea, maybe we can write a grant proposal for it.

**Comment by cmungall** [comment]
https://chat.openai.com/share/69dd5d8d-dc24-49bf-8ad3-68484504839d

(may not be visible if you're not a subscriber)

It should be possible to recapitulate this in openinterpreter

**Comment by pnrobinson** [comment]
![image](https://github.com/monarch-initiative/phenopacket-store/assets/4943420/580eaad3-2b7d-4de9-9399-d12b0192d341)

**Comment by pnrobinson** [comment]
I think this kind of pipeline is out of scope for this repo, although it would be useful. Here we want manually curated/checked curations!
