### ISSUE TITLE
Add my ORCID to FTH1 

### ISSUE THREAD

**Issue by leokim-l** [monarch-initiative/phenopacket-store#92]
@pnrobinson 

You asked me to add my ORCID to the phenopacket I created, but I don't know how to do that.

At:
https://github.com/monarch-initiative/phenopacket-store/blob/main/notebooks/FTH1/FTH1_NBIA9_individuals.ipynb

From:
created_by = "0000-0002-0736-9199"

To:
created_by = ["0000-0002-0736-9199", "0000-0002-6912-8518"]

Or let me know how to do so myself.

Cheers

**Comment by pnrobinson** [comment]
fixed with latest push
