### ISSUE TITLE
Create a stable download URL and link to it in the documentation

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/phenopacket-store#95]
Many computational users will want to download all phenopackets at once

This is available from:
https://github.com/monarch-initiative/phenopacket-store/releases

Versioned URLs are visible here like:
https://github.com/monarch-initiative/phenopacket-store/releases/download/0.1.11/all_phenopackets.tgz

It's not obvious from GitHub but it's possible to construct a URL that always resolves to the latest tgv:

https://github.com/monarch-initiative/phenopacket-store/releases/latest/download/all_phenopackets.tgz

Should we link to this from the docs?

Note that we don't want to be locked in to github forever (remember when we thought Jenkins was a good release vehicle), it would be good to provide stable PURLs for both the latest version and versioned releases.

I would favor one of two mechanisms here:

1. Register a w3id that redirects to the github releases page
2. Sync this repo with zenodo

1 is super lightweight, but is more of a surface layer, it's likely people will still bookmark github

2 sounds more involved but is actually super lightweight, we do this for a lot of software and data repos. It just involves going to https://zenodo.org/account/settings/github/, flipping a switch, and then zenodo and this repo will be synced. There will be a permanent DOI for the whole dataset, and individual release DOIs as well. The DOI will resolve to a zenodo metadata page and there will be bundled tgzs.

Here is an example:

- [![DOI](https://zenodo.org/badge/13996/linkml/linkml.svg)](https://zenodo.org/badge/latestdoi/13996/linkml/linkml)

cc @matentzn

**Comment by matentzn** [comment]
I am working on a plan with Kevin, Harry and Sierra, and it would fit to simply keep using GitHub releases for now. It involves creating monarch level purls.

**Comment by pnrobinson** [comment]
@matentzn 
We heard from the journal that the reviewers are starting to return reviews and so it would be awesome to have a GitHub release-level PURL to mention in the article.

**Comment by matentzn** [comment]
Ok, started working on this but need a moment to do this. Whats the timeline?

**Comment by ielis** [comment]
The stable URLs are now mentioned both in [README](https://github.com/monarch-initiative/phenopacket-store) and [docs](https://monarch-initiative.github.io/phenopacket-store).

We still may want to tag a release for the paper, so I'll leave this open.

**Comment by cmungall** [comment]
I still think zenodo and/or PURLs is a good idea

**Comment by pnrobinson** [comment]
@cmungall is there a tutorial for the zenodo option?

**Comment by ielis** [comment]
Based on 1st post of Chris in this thread, I went to https://zenodo.org/account/settings/github/, logged in with my GitHub credentials, and flipped the switch for Phenopacket store.

Now Zenodo waits until we make next release, and then it will provide us with a DOI & a DOI badge.

One thing to note, though. Zenodo states:
> ... Zenodo will automatically download a .zip-ball of each new release and register a DOI. ...

In our case, the .zip-ball is the repo itself (notebooks, input files, ...), and not the release ZIP/TARGZ archive. The repo zip ball seems to be complementary to the release archives. In other words, we definitely need *both* the zip ball and PURLs for the release archives.
We'll have both after we're done with Zenodo setup.

For the next steps, let's keep this open until we make the first Zenodo release!

**Comment by ielis** [comment]
After releasing `0.1.16` today, we have the first Zenodo snapshot:

[![DOI](https://zenodo.org/badge/580002593.svg)](https://zenodo.org/doi/10.5281/zenodo.13168726)
